### ISSUE TITLE
Add ability to publish Golang bindings to non-github.com repositories

### ISSUE THREAD

**Issue by partha04patel** [cdklabs/publib#664]
Publib throws an error if someone tries to publish Go code to a non-github.com repository, such as GitHub enterprise (github.mycompany.com) or other locations like Bitbucket: https://github.com/cdklabs/publib/blob/main/src/targets/go.ts#L262

It would be nice to have the option to publish to GitHub enterprise and Bitbucket repos in addition to github.com for people that want to publish their Go code to internal repositories.

**Comment by partha04patel** [comment]
I'd still like to see this be considered.

**Comment by eknowles** [comment]
I'd like to do this also with artifactory, but i can't see any maintainers of this?

**Comment by mrgrain** [comment]
We can't just remove the check because we are [cloning the repo](https://github.com/cdklabs/publib/blob/main/src/targets/go.ts#L171) with [credentials](https://github.com/cdklabs/publib/blob/main/src/help/git.ts#L19) so we can later publish (push) the release as a tag.
This makes a (large) assumption that the auth is for GitHub.

It _might_ actually work for other providers as well, but we will need to check and potentially warn.
